# Generated by Django 4.1.4 on 2022-12-11 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=100)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('km_troca_oleo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(auto_now=True)),
                ('hora_saida', models.TimeField(auto_now=True)),
                ('km_saida', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=150)),
                ('data_retorno', models.DateField()),
                ('hora_retorno', models.TimeField()),
                ('km_retorno', models.CharField(max_length=10)),
                ('km_percorrido', models.CharField(max_length=10)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo')),
            ],
        ),
    ]
