# Generated by Django 4.1.4 on 2022-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='data_saida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controle',
            name='hora_saida',
            field=models.TimeField(),
        ),
    ]
