# Generated by Django 4.1.4 on 2022-12-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_controle_data_saida_alter_controle_hora_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motorista'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo'),
        ),
    ]
